// <auto-generated />
using AuctionProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuctionProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuctionProject.Models.Auction", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.HasKey("AuctionId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            AuctionId = 1,
                            ProductId = 1,
                            SellerId = 1
                        },
                        new
                        {
                            AuctionId = 2,
                            ProductId = 2,
                            SellerId = 2
                        });
                });

            modelBuilder.Entity("AuctionProject.Models.AuctionBid", b =>
                {
                    b.Property<int>("AuctionBidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<double>("BidAmount")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuctionBidId");

                    b.HasIndex("AuctionId");

                    b.ToTable("AuctionBids");

                    b.HasData(
                        new
                        {
                            AuctionBidId = 1,
                            AuctionId = 1,
                            BidAmount = 18.5,
                            UserId = 1
                        },
                        new
                        {
                            AuctionBidId = 3,
                            AuctionId = 1,
                            BidAmount = 20.300000000000001,
                            UserId = 2
                        },
                        new
                        {
                            AuctionBidId = 2,
                            AuctionId = 2,
                            BidAmount = 20.0,
                            UserId = 2
                        },
                        new
                        {
                            AuctionBidId = 4,
                            AuctionId = 2,
                            BidAmount = 23.5,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("AuctionProject.Models.AuctionBid", b =>
                {
                    b.HasOne("AuctionProject.Models.Auction", "Auction")
                        .WithMany("AuctionBid")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
